//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.Core.Logic.DM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionsRoute
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ActionsRoute()
        {
            this.CategoriesActionsRoutes = new HashSet<CategoriesActionsRoute>();
            this.TicketCategoriesActionsRoutes = new HashSet<TicketCategoriesActionsRoute>();
        }
    
        public long ActionsRouteId { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public bool Enable { get; set; }
        public byte[] RowVersion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoriesActionsRoute> CategoriesActionsRoutes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketCategoriesActionsRoute> TicketCategoriesActionsRoutes { get; set; }
    }
}
