//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.Core.Logic.DM
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketAudit
    {
        public long TicketAuditId { get; set; }
        public string UserId { get; set; }
        public long TicketId { get; set; }
        public Nullable<long> TicketStatusId { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public string Comment { get; set; }
        public byte[] RowVersion { get; set; }
        public Nullable<long> PriorityId { get; set; }
        public Nullable<long> DepartmentId { get; set; }
        public Nullable<long> TicketActionsId { get; set; }
    
        public virtual TicketStatus TicketStatus { get; set; }
        public virtual Priority Priority { get; set; }
        public virtual TicketAction TicketAction { get; set; }
        public virtual Ticket Ticket { get; set; }
    }
}
