//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.Core.Logic.DM
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketCategoriesAction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TicketCategoriesAction()
        {
            this.TicketCategoriesActionsRoutes = new HashSet<TicketCategoriesActionsRoute>();
            this.TicketCategoriesActionsNotifications = new HashSet<TicketCategoriesActionsNotification>();
        }
    
        public long TicketCategoriesActionsId { get; set; }
        public Nullable<long> TicketParentId { get; set; }
        public long TicketCategoriesId { get; set; }
        public long TicketStatusesId { get; set; }
        public Nullable<long> TicketCategoriesDestinationId { get; set; }
        public Nullable<long> TicketStatusesDestinationId { get; set; }
        public long TicketActionsId { get; set; }
        public string Description { get; set; }
        public byte[] RowVersion { get; set; }
        public Nullable<int> BankId { get; set; }
        public Nullable<long> ChannelId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual TicketAction TicketAction { get; set; }
        public virtual TicketStatus TicketStatus { get; set; }
        public virtual TicketStatus TicketStatus1 { get; set; }
        public virtual Channel Channel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketCategoriesActionsRoute> TicketCategoriesActionsRoutes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TicketCategoriesActionsNotification> TicketCategoriesActionsNotifications { get; set; }
    }
}
