//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtlasMngr.WCFProfile {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseRequest", Namespace="http://www.pin-pay.com/schemas/Requests/DTO")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AtlasMngr.WCFProfile.RemoveDeviceRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AtlasMngr.WCFProfile.ResetPinRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AtlasMngr.WCFProfile.BlackListRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AtlasMngr.WCFProfile.ProfileRequest))]
    public partial class BaseRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AtlasMngr.WCFProfile.GenericRequest RequestField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AtlasMngr.WCFProfile.GenericRequest Request {
            get {
                return this.RequestField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestField, value) != true)) {
                    this.RequestField = value;
                    this.RaisePropertyChanged("Request");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenericRequest", Namespace="http://www.pin-pay.com/schemas/Requests/DTO")]
    [System.SerializableAttribute()]
    public partial class GenericRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RequestDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RequestDate {
            get {
                return this.RequestDateField;
            }
            set {
                if ((this.RequestDateField.Equals(value) != true)) {
                    this.RequestDateField = value;
                    this.RaisePropertyChanged("RequestDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestId {
            get {
                return this.RequestIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestIdField, value) != true)) {
                    this.RequestIdField = value;
                    this.RaisePropertyChanged("RequestId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RemoveDeviceRequest", Namespace="http://www.pin-pay.com/schemas/ProfileService/Requests")]
    [System.SerializableAttribute()]
    public partial class RemoveDeviceRequest : AtlasMngr.WCFProfile.BaseRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DeviceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AtlasMngr.WCFProfile.Header HeaderField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DeviceId {
            get {
                return this.DeviceIdField;
            }
            set {
                if ((this.DeviceIdField.Equals(value) != true)) {
                    this.DeviceIdField = value;
                    this.RaisePropertyChanged("DeviceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AtlasMngr.WCFProfile.Header Header {
            get {
                return this.HeaderField;
            }
            set {
                if ((object.ReferenceEquals(this.HeaderField, value) != true)) {
                    this.HeaderField = value;
                    this.RaisePropertyChanged("Header");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResetPinRequest", Namespace="http://www.pin-pay.com/schemas/ProfileService/Requests")]
    [System.SerializableAttribute()]
    public partial class ResetPinRequest : AtlasMngr.WCFProfile.BaseRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AtlasMngr.WCFProfile.Header HeaderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PinField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AtlasMngr.WCFProfile.Header Header {
            get {
                return this.HeaderField;
            }
            set {
                if ((object.ReferenceEquals(this.HeaderField, value) != true)) {
                    this.HeaderField = value;
                    this.RaisePropertyChanged("Header");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pin {
            get {
                return this.PinField;
            }
            set {
                if ((object.ReferenceEquals(this.PinField, value) != true)) {
                    this.PinField = value;
                    this.RaisePropertyChanged("Pin");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BlackListRequest", Namespace="http://www.pin-pay.com/schemas/ProfileService/Requests")]
    [System.SerializableAttribute()]
    public partial class BlackListRequest : AtlasMngr.WCFProfile.BaseRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AtlasMngr.WCFProfile.Header HeaderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AtlasMngr.WCFProfile.Header Header {
            get {
                return this.HeaderField;
            }
            set {
                if ((object.ReferenceEquals(this.HeaderField, value) != true)) {
                    this.HeaderField = value;
                    this.RaisePropertyChanged("Header");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonField, value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProfileRequest", Namespace="http://www.pin-pay.com/schemas/ProfileService/Requests")]
    [System.SerializableAttribute()]
    public partial class ProfileRequest : AtlasMngr.WCFProfile.BaseRequest {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AtlasMngr.WCFProfile.Header HeaderField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AtlasMngr.WCFProfile.Header Header {
            get {
                return this.HeaderField;
            }
            set {
                if ((object.ReferenceEquals(this.HeaderField, value) != true)) {
                    this.HeaderField = value;
                    this.RaisePropertyChanged("Header");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Header", Namespace="http://schemas.datacontract.org/2004/07/PinPayProfile.WCF.ProfileService.DTO.Data" +
        "Object")]
    [System.SerializableAttribute()]
    public partial class Header : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string APIKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BankIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string APIKey {
            get {
                return this.APIKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.APIKeyField, value) != true)) {
                    this.APIKeyField = value;
                    this.RaisePropertyChanged("APIKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BankId {
            get {
                return this.BankIdField;
            }
            set {
                if ((this.BankIdField.Equals(value) != true)) {
                    this.BankIdField = value;
                    this.RaisePropertyChanged("BankId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileNumber {
            get {
                return this.MobileNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileNumberField, value) != true)) {
                    this.MobileNumberField = value;
                    this.RaisePropertyChanged("MobileNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseResponse", Namespace="http://www.pin-pay.com/schemas/Responses/DTO")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(AtlasMngr.WCFProfile.ProfileResponse))]
    public partial class BaseResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AtlasMngr.WCFProfile.GenericResponse ResponseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AtlasMngr.WCFProfile.GenericResponse Response {
            get {
                return this.ResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponseField, value) != true)) {
                    this.ResponseField = value;
                    this.RaisePropertyChanged("Response");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenericResponse", Namespace="http://www.pin-pay.com/schemas/Responses/DTO")]
    [System.SerializableAttribute()]
    public partial class GenericResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Exception ExceptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FunctionNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSuccessfullField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ResponseDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AtlasMngr.WCFProfile.ResultCode ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResultCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AtlasMngr.WCFProfile.ServerInfo ServerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Exception Exception {
            get {
                return this.ExceptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionField, value) != true)) {
                    this.ExceptionField = value;
                    this.RaisePropertyChanged("Exception");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FunctionName {
            get {
                return this.FunctionNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FunctionNameField, value) != true)) {
                    this.FunctionNameField = value;
                    this.RaisePropertyChanged("FunctionName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccessfull {
            get {
                return this.IsSuccessfullField;
            }
            set {
                if ((this.IsSuccessfullField.Equals(value) != true)) {
                    this.IsSuccessfullField = value;
                    this.RaisePropertyChanged("IsSuccessfull");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestId {
            get {
                return this.RequestIdField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestIdField, value) != true)) {
                    this.RequestIdField = value;
                    this.RaisePropertyChanged("RequestId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ResponseDate {
            get {
                return this.ResponseDateField;
            }
            set {
                if ((this.ResponseDateField.Equals(value) != true)) {
                    this.ResponseDateField = value;
                    this.RaisePropertyChanged("ResponseDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AtlasMngr.WCFProfile.ResultCode Result {
            get {
                return this.ResultField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultField, value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResultCode {
            get {
                return this.ResultCodeField;
            }
            set {
                if ((this.ResultCodeField.Equals(value) != true)) {
                    this.ResultCodeField = value;
                    this.RaisePropertyChanged("ResultCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AtlasMngr.WCFProfile.ServerInfo Server {
            get {
                return this.ServerField;
            }
            set {
                if ((object.ReferenceEquals(this.ServerField, value) != true)) {
                    this.ServerField = value;
                    this.RaisePropertyChanged("Server");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProfileResponse", Namespace="http://www.pin-pay.com/schemas/ProfileService/Responses")]
    [System.SerializableAttribute()]
    public partial class ProfileResponse : AtlasMngr.WCFProfile.BaseResponse {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AtlasMngr.WCFProfile.FullProfile ProfileField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AtlasMngr.WCFProfile.FullProfile Profile {
            get {
                return this.ProfileField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfileField, value) != true)) {
                    this.ProfileField = value;
                    this.RaisePropertyChanged("Profile");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FullProfile", Namespace="http://schemas.datacontract.org/2004/07/PinPayProfile.WCF.ProfileService.DTO.Data" +
        "Object")]
    [System.SerializableAttribute()]
    public partial class FullProfile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AtlasMngr.WCFProfile.Device[] DevicesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AtlasMngr.WCFProfile.Profile ProfileInfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AtlasMngr.WCFProfile.Device[] Devices {
            get {
                return this.DevicesField;
            }
            set {
                if ((object.ReferenceEquals(this.DevicesField, value) != true)) {
                    this.DevicesField = value;
                    this.RaisePropertyChanged("Devices");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AtlasMngr.WCFProfile.Profile ProfileInfo {
            get {
                return this.ProfileInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProfileInfoField, value) != true)) {
                    this.ProfileInfoField = value;
                    this.RaisePropertyChanged("ProfileInfo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultCode", Namespace="http://www.pin-pay.com/schemas/DTO")]
    [System.SerializableAttribute()]
    public partial class ResultCode : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ValField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Val {
            get {
                return this.ValField;
            }
            set {
                if ((this.ValField.Equals(value) != true)) {
                    this.ValField = value;
                    this.RaisePropertyChanged("Val");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServerInfo", Namespace="http://www.pin-pay.com/schemas/DTO")]
    [System.SerializableAttribute()]
    public partial class ServerInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HostNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IPField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HostName {
            get {
                return this.HostNameField;
            }
            set {
                if ((object.ReferenceEquals(this.HostNameField, value) != true)) {
                    this.HostNameField = value;
                    this.RaisePropertyChanged("HostName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IP {
            get {
                return this.IPField;
            }
            set {
                if ((object.ReferenceEquals(this.IPField, value) != true)) {
                    this.IPField = value;
                    this.RaisePropertyChanged("IP");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Profile", Namespace="http://schemas.datacontract.org/2004/07/PinPayProfile.WCF.ProfileService.DTO.Data" +
        "Object")]
    [System.SerializableAttribute()]
    public partial class Profile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BlackListReasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EnrollmentDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsBlackListedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ProfileIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StatusSinceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BlackListReason {
            get {
                return this.BlackListReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.BlackListReasonField, value) != true)) {
                    this.BlackListReasonField = value;
                    this.RaisePropertyChanged("BlackListReason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EnrollmentDate {
            get {
                return this.EnrollmentDateField;
            }
            set {
                if ((this.EnrollmentDateField.Equals(value) != true)) {
                    this.EnrollmentDateField = value;
                    this.RaisePropertyChanged("EnrollmentDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsBlackListed {
            get {
                return this.IsBlackListedField;
            }
            set {
                if ((this.IsBlackListedField.Equals(value) != true)) {
                    this.IsBlackListedField = value;
                    this.RaisePropertyChanged("IsBlackListed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileNumber {
            get {
                return this.MobileNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileNumberField, value) != true)) {
                    this.MobileNumberField = value;
                    this.RaisePropertyChanged("MobileNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ProfileId {
            get {
                return this.ProfileIdField;
            }
            set {
                if ((this.ProfileIdField.Equals(value) != true)) {
                    this.ProfileIdField = value;
                    this.RaisePropertyChanged("ProfileId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StatusSince {
            get {
                return this.StatusSinceField;
            }
            set {
                if ((this.StatusSinceField.Equals(value) != true)) {
                    this.StatusSinceField = value;
                    this.RaisePropertyChanged("StatusSince");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Device", Namespace="http://schemas.datacontract.org/2004/07/PinPayProfile.WCF.ProfileService.DTO.Data" +
        "Object")]
    [System.SerializableAttribute()]
    public partial class Device : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long DeviceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeviceNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlatformField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long DeviceId {
            get {
                return this.DeviceIdField;
            }
            set {
                if ((this.DeviceIdField.Equals(value) != true)) {
                    this.DeviceIdField = value;
                    this.RaisePropertyChanged("DeviceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeviceName {
            get {
                return this.DeviceNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceNameField, value) != true)) {
                    this.DeviceNameField = value;
                    this.RaisePropertyChanged("DeviceName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Platform {
            get {
                return this.PlatformField;
            }
            set {
                if ((object.ReferenceEquals(this.PlatformField, value) != true)) {
                    this.PlatformField = value;
                    this.RaisePropertyChanged("Platform");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogLevel", Namespace="http://www.pin-pay.com/schemas/DTO")]
    [System.SerializableAttribute()]
    public partial class LogLevel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ValField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Val {
            get {
                return this.ValField;
            }
            set {
                if ((this.ValField.Equals(value) != true)) {
                    this.ValField = value;
                    this.RaisePropertyChanged("Val");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.pin-pay.com/schemas/ProfileService", ConfigurationName="WCFProfile.IProfileService")]
    public interface IProfileService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pin-pay.com/schemas/ProfileService/IProfileService/GetProfile", ReplyAction="http://www.pin-pay.com/schemas/ProfileService/IProfileService/GetProfileResponse")]
        AtlasMngr.WCFProfile.ProfileResponse GetProfile(AtlasMngr.WCFProfile.ProfileRequest pRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pin-pay.com/schemas/ProfileService/IProfileService/GetProfile", ReplyAction="http://www.pin-pay.com/schemas/ProfileService/IProfileService/GetProfileResponse")]
        System.Threading.Tasks.Task<AtlasMngr.WCFProfile.ProfileResponse> GetProfileAsync(AtlasMngr.WCFProfile.ProfileRequest pRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pin-pay.com/schemas/ProfileService/IProfileService/RemoveDevice", ReplyAction="http://www.pin-pay.com/schemas/ProfileService/IProfileService/RemoveDeviceRespons" +
            "e")]
        AtlasMngr.WCFProfile.BaseResponse RemoveDevice(AtlasMngr.WCFProfile.RemoveDeviceRequest pRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pin-pay.com/schemas/ProfileService/IProfileService/RemoveDevice", ReplyAction="http://www.pin-pay.com/schemas/ProfileService/IProfileService/RemoveDeviceRespons" +
            "e")]
        System.Threading.Tasks.Task<AtlasMngr.WCFProfile.BaseResponse> RemoveDeviceAsync(AtlasMngr.WCFProfile.RemoveDeviceRequest pRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pin-pay.com/schemas/ProfileService/IProfileService/ResetPin", ReplyAction="http://www.pin-pay.com/schemas/ProfileService/IProfileService/ResetPinResponse")]
        AtlasMngr.WCFProfile.BaseResponse ResetPin(AtlasMngr.WCFProfile.ResetPinRequest pRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pin-pay.com/schemas/ProfileService/IProfileService/ResetPin", ReplyAction="http://www.pin-pay.com/schemas/ProfileService/IProfileService/ResetPinResponse")]
        System.Threading.Tasks.Task<AtlasMngr.WCFProfile.BaseResponse> ResetPinAsync(AtlasMngr.WCFProfile.ResetPinRequest pRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pin-pay.com/schemas/ProfileService/IProfileService/Block", ReplyAction="http://www.pin-pay.com/schemas/ProfileService/IProfileService/BlockResponse")]
        AtlasMngr.WCFProfile.BaseResponse Block(AtlasMngr.WCFProfile.ProfileRequest pRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pin-pay.com/schemas/ProfileService/IProfileService/Block", ReplyAction="http://www.pin-pay.com/schemas/ProfileService/IProfileService/BlockResponse")]
        System.Threading.Tasks.Task<AtlasMngr.WCFProfile.BaseResponse> BlockAsync(AtlasMngr.WCFProfile.ProfileRequest pRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pin-pay.com/schemas/ProfileService/IProfileService/Cancel", ReplyAction="http://www.pin-pay.com/schemas/ProfileService/IProfileService/CancelResponse")]
        AtlasMngr.WCFProfile.BaseResponse Cancel(AtlasMngr.WCFProfile.ProfileRequest pRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pin-pay.com/schemas/ProfileService/IProfileService/Cancel", ReplyAction="http://www.pin-pay.com/schemas/ProfileService/IProfileService/CancelResponse")]
        System.Threading.Tasks.Task<AtlasMngr.WCFProfile.BaseResponse> CancelAsync(AtlasMngr.WCFProfile.ProfileRequest pRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pin-pay.com/schemas/ProfileService/IProfileService/BlackList", ReplyAction="http://www.pin-pay.com/schemas/ProfileService/IProfileService/BlackListResponse")]
        AtlasMngr.WCFProfile.BaseResponse BlackList(AtlasMngr.WCFProfile.BlackListRequest pRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pin-pay.com/schemas/ProfileService/IProfileService/BlackList", ReplyAction="http://www.pin-pay.com/schemas/ProfileService/IProfileService/BlackListResponse")]
        System.Threading.Tasks.Task<AtlasMngr.WCFProfile.BaseResponse> BlackListAsync(AtlasMngr.WCFProfile.BlackListRequest pRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pin-pay.com/schemas/ProfileService/IProfileService/UnBlackList", ReplyAction="http://www.pin-pay.com/schemas/ProfileService/IProfileService/UnBlackListResponse" +
            "")]
        AtlasMngr.WCFProfile.BaseResponse UnBlackList(AtlasMngr.WCFProfile.ProfileRequest pRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pin-pay.com/schemas/ProfileService/IProfileService/UnBlackList", ReplyAction="http://www.pin-pay.com/schemas/ProfileService/IProfileService/UnBlackListResponse" +
            "")]
        System.Threading.Tasks.Task<AtlasMngr.WCFProfile.BaseResponse> UnBlackListAsync(AtlasMngr.WCFProfile.ProfileRequest pRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pin-pay.com/schemas/ProfileService/IProfileService/Ping", ReplyAction="http://www.pin-pay.com/schemas/ProfileService/IProfileService/PingResponse")]
        bool Ping();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pin-pay.com/schemas/ProfileService/IProfileService/Ping", ReplyAction="http://www.pin-pay.com/schemas/ProfileService/IProfileService/PingResponse")]
        System.Threading.Tasks.Task<bool> PingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pin-pay.com/schemas/ProfileService/IProfileService/StopService", ReplyAction="http://www.pin-pay.com/schemas/ProfileService/IProfileService/StopServiceResponse" +
            "")]
        void StopService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pin-pay.com/schemas/ProfileService/IProfileService/StopService", ReplyAction="http://www.pin-pay.com/schemas/ProfileService/IProfileService/StopServiceResponse" +
            "")]
        System.Threading.Tasks.Task StopServiceAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pin-pay.com/schemas/ProfileService/IProfileService/StartService", ReplyAction="http://www.pin-pay.com/schemas/ProfileService/IProfileService/StartServiceRespons" +
            "e")]
        void StartService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pin-pay.com/schemas/ProfileService/IProfileService/StartService", ReplyAction="http://www.pin-pay.com/schemas/ProfileService/IProfileService/StartServiceRespons" +
            "e")]
        System.Threading.Tasks.Task StartServiceAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pin-pay.com/schemas/ProfileService/IProfileService/ResetServiceCache", ReplyAction="http://www.pin-pay.com/schemas/ProfileService/IProfileService/ResetServiceCacheRe" +
            "sponse")]
        bool ResetServiceCache();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pin-pay.com/schemas/ProfileService/IProfileService/ResetServiceCache", ReplyAction="http://www.pin-pay.com/schemas/ProfileService/IProfileService/ResetServiceCacheRe" +
            "sponse")]
        System.Threading.Tasks.Task<bool> ResetServiceCacheAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pin-pay.com/schemas/ProfileService/IProfileService/SetServiceLogLevel", ReplyAction="http://www.pin-pay.com/schemas/ProfileService/IProfileService/SetServiceLogLevelR" +
            "esponse")]
        void SetServiceLogLevel(AtlasMngr.WCFProfile.LogLevel pLogLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pin-pay.com/schemas/ProfileService/IProfileService/SetServiceLogLevel", ReplyAction="http://www.pin-pay.com/schemas/ProfileService/IProfileService/SetServiceLogLevelR" +
            "esponse")]
        System.Threading.Tasks.Task SetServiceLogLevelAsync(AtlasMngr.WCFProfile.LogLevel pLogLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pin-pay.com/schemas/ProfileService/IProfileService/SetVersion", ReplyAction="http://www.pin-pay.com/schemas/ProfileService/IProfileService/SetVersionResponse")]
        void SetVersion(string pVersion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pin-pay.com/schemas/ProfileService/IProfileService/SetVersion", ReplyAction="http://www.pin-pay.com/schemas/ProfileService/IProfileService/SetVersionResponse")]
        System.Threading.Tasks.Task SetVersionAsync(string pVersion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pin-pay.com/schemas/ProfileService/IProfileService/RetrieveVersion", ReplyAction="http://www.pin-pay.com/schemas/ProfileService/IProfileService/RetrieveVersionResp" +
            "onse")]
        string RetrieveVersion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.pin-pay.com/schemas/ProfileService/IProfileService/RetrieveVersion", ReplyAction="http://www.pin-pay.com/schemas/ProfileService/IProfileService/RetrieveVersionResp" +
            "onse")]
        System.Threading.Tasks.Task<string> RetrieveVersionAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProfileServiceChannel : AtlasMngr.WCFProfile.IProfileService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProfileServiceClient : System.ServiceModel.ClientBase<AtlasMngr.WCFProfile.IProfileService>, AtlasMngr.WCFProfile.IProfileService {
        
        public ProfileServiceClient() {
        }
        
        public ProfileServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProfileServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProfileServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProfileServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AtlasMngr.WCFProfile.ProfileResponse GetProfile(AtlasMngr.WCFProfile.ProfileRequest pRequest) {
            return base.Channel.GetProfile(pRequest);
        }
        
        public System.Threading.Tasks.Task<AtlasMngr.WCFProfile.ProfileResponse> GetProfileAsync(AtlasMngr.WCFProfile.ProfileRequest pRequest) {
            return base.Channel.GetProfileAsync(pRequest);
        }
        
        public AtlasMngr.WCFProfile.BaseResponse RemoveDevice(AtlasMngr.WCFProfile.RemoveDeviceRequest pRequest) {
            return base.Channel.RemoveDevice(pRequest);
        }
        
        public System.Threading.Tasks.Task<AtlasMngr.WCFProfile.BaseResponse> RemoveDeviceAsync(AtlasMngr.WCFProfile.RemoveDeviceRequest pRequest) {
            return base.Channel.RemoveDeviceAsync(pRequest);
        }
        
        public AtlasMngr.WCFProfile.BaseResponse ResetPin(AtlasMngr.WCFProfile.ResetPinRequest pRequest) {
            return base.Channel.ResetPin(pRequest);
        }
        
        public System.Threading.Tasks.Task<AtlasMngr.WCFProfile.BaseResponse> ResetPinAsync(AtlasMngr.WCFProfile.ResetPinRequest pRequest) {
            return base.Channel.ResetPinAsync(pRequest);
        }
        
        public AtlasMngr.WCFProfile.BaseResponse Block(AtlasMngr.WCFProfile.ProfileRequest pRequest) {
            return base.Channel.Block(pRequest);
        }
        
        public System.Threading.Tasks.Task<AtlasMngr.WCFProfile.BaseResponse> BlockAsync(AtlasMngr.WCFProfile.ProfileRequest pRequest) {
            return base.Channel.BlockAsync(pRequest);
        }
        
        public AtlasMngr.WCFProfile.BaseResponse Cancel(AtlasMngr.WCFProfile.ProfileRequest pRequest) {
            return base.Channel.Cancel(pRequest);
        }
        
        public System.Threading.Tasks.Task<AtlasMngr.WCFProfile.BaseResponse> CancelAsync(AtlasMngr.WCFProfile.ProfileRequest pRequest) {
            return base.Channel.CancelAsync(pRequest);
        }
        
        public AtlasMngr.WCFProfile.BaseResponse BlackList(AtlasMngr.WCFProfile.BlackListRequest pRequest) {
            return base.Channel.BlackList(pRequest);
        }
        
        public System.Threading.Tasks.Task<AtlasMngr.WCFProfile.BaseResponse> BlackListAsync(AtlasMngr.WCFProfile.BlackListRequest pRequest) {
            return base.Channel.BlackListAsync(pRequest);
        }
        
        public AtlasMngr.WCFProfile.BaseResponse UnBlackList(AtlasMngr.WCFProfile.ProfileRequest pRequest) {
            return base.Channel.UnBlackList(pRequest);
        }
        
        public System.Threading.Tasks.Task<AtlasMngr.WCFProfile.BaseResponse> UnBlackListAsync(AtlasMngr.WCFProfile.ProfileRequest pRequest) {
            return base.Channel.UnBlackListAsync(pRequest);
        }
        
        public bool Ping() {
            return base.Channel.Ping();
        }
        
        public System.Threading.Tasks.Task<bool> PingAsync() {
            return base.Channel.PingAsync();
        }
        
        public void StopService() {
            base.Channel.StopService();
        }
        
        public System.Threading.Tasks.Task StopServiceAsync() {
            return base.Channel.StopServiceAsync();
        }
        
        public void StartService() {
            base.Channel.StartService();
        }
        
        public System.Threading.Tasks.Task StartServiceAsync() {
            return base.Channel.StartServiceAsync();
        }
        
        public bool ResetServiceCache() {
            return base.Channel.ResetServiceCache();
        }
        
        public System.Threading.Tasks.Task<bool> ResetServiceCacheAsync() {
            return base.Channel.ResetServiceCacheAsync();
        }
        
        public void SetServiceLogLevel(AtlasMngr.WCFProfile.LogLevel pLogLevel) {
            base.Channel.SetServiceLogLevel(pLogLevel);
        }
        
        public System.Threading.Tasks.Task SetServiceLogLevelAsync(AtlasMngr.WCFProfile.LogLevel pLogLevel) {
            return base.Channel.SetServiceLogLevelAsync(pLogLevel);
        }
        
        public void SetVersion(string pVersion) {
            base.Channel.SetVersion(pVersion);
        }
        
        public System.Threading.Tasks.Task SetVersionAsync(string pVersion) {
            return base.Channel.SetVersionAsync(pVersion);
        }
        
        public string RetrieveVersion() {
            return base.Channel.RetrieveVersion();
        }
        
        public System.Threading.Tasks.Task<string> RetrieveVersionAsync() {
            return base.Channel.RetrieveVersionAsync();
        }
    }
}
